### PR TITLE
Add italian translation

### PR DESCRIPTION
**Pull request by digitall-it**

### CODE REVIEW

**Comment by dhensby** [comment]
Thanks so much

**Comment by tractorcow** [comment]
These will need to be updated at https://www.transifex.com/silverstripe/silverstripe-secureassets/, otherwise next release they will be wiped.

**Comment by digitall-it** [comment]
Been there, done that! ;)

**Comment by tractorcow** [comment]
Oh you are the awesome-est. :) Thanks @digitall-it

**Pull request merged**
